repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix]
    # Sort imports
    - id: ruff
      args: [--select, I, --fix]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/srstevenson/nb-clean
  rev: 3.3.0
  hooks:
    - id: nb-clean
- repo: local
  hooks:
    - id: check-uv-lock
      name: Check UV Lock
      entry: |
        bash -c '
        if ! uv lock --check; then
            echo "uv.lock is out of date. You need to update it"
            exit 1
        else
            echo "uv.lock is up-to-date with pyproject.toml."
        fi'
      language: system
      stages: [pre-commit]