engine:
  download:
    end_year: 2020
    max_per_year: 1
    start_year: 2010
  output:
    folder_name: "output"
    predefined_themes_file_name: "predefined_themes.yaml"
    themes_file_name: "themes.yaml"
    summary_file_name: "summary.csv"
    reports:
    # Report ID is the only available variable.
      folder_name: "{{report_id}}" # This folder name should always have the report_id variable.
      text_file_name: "{{report_id}}.txt"
      safety_issues: "{{report_id}}_safety_issues.yaml"
      pdf_file_name: "{{report_id}}.pdf"
      themes_file_name: "{{report_id}}_themes.yaml"
      full_summary_file_name: "{{report_id}}_summary.yaml"
      weightings_file_name: "{{report_id}}_weightings.txt"
    recommendation_file_name: "TAIC_recommendations.csv"
  validation:
    folder_name: "validation"
    
