engine:
  download:
    end_year: 2024
    max_per_year: 100
    start_year: 2000
    ignored_reports: ['2022_202', '2022_203']
    modes: ['a', 'r','m']
    agencies: ['ATSB', 'TSB', 'TAIC']
  output:
    folder_name: "output"
    container_name: "engineoutput"
    report_pdf_folder_name: "report_pdfs"
    report_pdf_file_name: "{{report_id}}.pdf"
    parsed_reports_df_file_name: "parsed_reports.pkl"
    recommendations_df_file_name: "recommendations.pkl"
    all_event_types_df_file_name: "all_event_types.pkl"
    report_event_types_df_file_name: "report_event_types.pkl"
    report_titles_df_file_name: "report_titles.pkl"
    report_sections_df_file_name: "report_sections.pkl"
    important_text_df_file_name: "important_text.pkl"
    toc_df_file_name: "table_of_contents.pkl"
    safety_issues_df_file_name: "safety_issues.pkl"
    extracted_reports_df_file_name: "extracted_reports.pkl"
    recommendation_safety_issue_links_df_file_name: "recommendation_safety_issue_links.pkl"
    recommendation_response_classification_df_file_name: "recommendation_response_classification.pkl"
    atsb_website_safety_issues_file_name: "atsb_website_safety_issues.pkl"
    tsb_website_recommendations_file_name: "tsb_website_recommendations.pkl"
    taic_website_recommendations_file_name: "taic_website_recommendations.pkl"
    atsb_website_reports_table_file_name: "atsb_website_reports_table.pkl"
    taic_website_reports_table_file_name: "taic_website_reports_table.pkl"
    embeddings:
      folder_name: "embeddings"
      safety_issues_file_name: "safety_issues_embeddings_{{num}}.pkl"
      recommendations_file_name: "recommendations_embeddings_{{num}}.pkl"
      report_sections_file_name: "report_sections_embeddings_{{num}}.pkl"
      report_text_file_name: "report_text_embeddings_{{num}}.pkl"
  data:
    data_remote_folder_location: "https://raw.githubusercontent.com/1jamesthompson1/TAIC-report-summary/main/data/"
    data_local_folder_location: "data"
    event_types_file_name: "event_types.csv"
    atsb_historic_aviation: "atsb_historic_aviation_investigations.csv"
  validation:
    folder_name: "validation"
    
