engine:
  download:
    end_year: 2024
    max_per_year: 100
    start_year: 2000
    ignored_reports: ['2022_202', '2022_203']
  output:
    folder_name: "output"
    report_pdf_folder_name: "report_pdfs"
    report_pdf_file_name: "{{report_id}}.pdf"
    parsed_reports_df_file_name: "parsed_reports.pkl"
    recommendations_df_file_name: "recommendations.pkl"
    report_sections_df_file_name: "report_sections.pkl"
    important_text_df_file_name: "important_text.pkl"
    safety_issues_df_file_name: "safety_issues.pkl"
    extracted_reports_df_file_name: "extracted_reports.pkl"
    reports:
    # Report ID is the only available variable.
      folder_name: "{{report_id}}" # This folder name should always have the report_id variable.
      text_file_name: "{{report_id}}.txt"
      important_text_file_name: "{{report_id}}_important_text.yaml"
      safety_issues: "{{report_id}}_safety_issues.yaml"
      pdf_file_name: "{{report_id}}.pdf"
      themes_file_name: "{{report_id}}_themes.yaml"
      full_summary_file_name: "{{report_id}}_summary.yaml"
      weightings_file_name: "{{report_id}}_weightings.txt"
      recommendations_file_name: "{{report_id}}_recommendations.csv"
      recommendation_safety_issue_links_file_name: "{{report_id}}_recommendation_safety_issue_links.csv"
      recommendation_safety_issue_links_visual_file_name: "{{report_id}}_links_visual.png"
  data:
    data_hosted_folder_location: "https://raw.githubusercontent.com/1jamesthompson1/TAIC-report-summary/main/data/"
    recommendations_file_name: "cleaned_TAIC_recommendations_2024_04_04.csv"
  validation:
    folder_name: "validation"
    
