engine:
  download:
    end_year: 2020
    max_per_year: 1
    start_year: 2010
  output:
    folder_name: "output"
    predefined_themes_file_name: "predefined_themes.yaml"
    recommendation_responses_file_name: "recommendation_responses.csv"
    themes_file_name: "themes.yaml"
    summary_file_name: "summary.csv"
    reports:
    # Report ID is the only available variable.
      folder_name: "{{report_id}}" # This folder name should always have the report_id variable.
      text_file_name: "{{report_id}}.txt"
      safety_issues: "{{report_id}}_safety_issues.yaml"
      pdf_file_name: "{{report_id}}.pdf"
      themes_file_name: "{{report_id}}_themes.yaml"
      full_summary_file_name: "{{report_id}}_summary.yaml"
      weightings_file_name: "{{report_id}}_weightings.txt"
      recommendations_file_name: "{{report_id}}_recommendations.csv"
      recommendation_safety_issue_links_file_name: "{{report_id}}_recommendation_safety_issue_links.csv"
      recommendation_safety_issue_links_visual_file_name: "{{report_id}}_links_visual.png"
  data:
    recommendations_file_name: "cleaned_TAIC_recommendations_2024_04_04.csv"
  validation:
    folder_name: "validation"
    
