engine:
  download:
    end_year: 2023
    max_per_year: 15
    start_year: 2010
  output:
    folder_name: "output"
    themes_file_name: "themes.yaml"
    summary_file_name: "summary.csv"
    reports:
    # Report ID is the only available variable.
      folder_name: "{{report_id}}" # This folder name should always have the report_id variable.
      text_file_name: "{{report_id}}.txt"
      pdf_file_name: "{{report_id}}.pdf"
      themes_file_name: "{{report_id}}_themes.txt"
      summary_file_name: "{{report_id}}_summary.txt"


