engine:
  download:
    end_year: 2024
    max_per_year: 100
    start_year: 2000
    ignored_reports: ['2022_202', '2022_203']
  output:
    folder_name: "output"
    report_pdf_folder_name: "report_pdfs"
    report_pdf_file_name: "{{report_id}}.pdf"
    parsed_reports_df_file_name: "parsed_reports.pkl"
    recommendations_df_file_name: "recommendations.pkl"
    report_sections_df_file_name: "report_sections.pkl"
    important_text_df_file_name: "important_text.pkl"
    safety_issues_df_file_name: "safety_issues.pkl"
    extracted_reports_df_file_name: "extracted_reports.pkl"
    recommendation_safety_issue_links_df_file_name: "recommendation_safety_issue_links.pkl"
    recommendation_response_classification_df_file_name: "recommendation_response_classification.pkl"
  data:
    data_hosted_folder_location: "https://raw.githubusercontent.com/1jamesthompson1/TAIC-report-summary/main/data/"
    recommendations_file_name: "cleaned_TAIC_recommendations_2024_04_04.csv"
  validation:
    folder_name: "validation"
    
