engine:
  download:
    end_year: 2023
    max_per_year: 15
    start_year: 2010
    modes: ["a", "r", "m"]
  output:
    folder_name: "output"
    themes_file_name: "themes.yaml"
    summary_file_name: "summary.csv"
    reports:
    # Report ID is the only available variable.
      folder_name: "{{report_id}}" # This folder name should always have the report_id variable.
      text_file_name: "{{report_id}}.txt"
      pdf_file_name: "{{report_id}}.pdf"
      themes_file_name: "{{report_id}}_themes.txt"
      full_summary_file_name: "{{report_id}}_summary.txt"
      weightings_file_name: "{{report_id}}_weightings.txt"
  validation:
    folder_name: "validation"
    
