version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=viewer/app.py
