[tool.poetry]
name = "taic-report-engine"
version = "0.1.0"
description = "An engine to use the powers of LLMs offered by openai to help analyse and interpret the accident investigation reports."
authors = ["James <1jamesthompson1@gmail.com>"]
license = "GPLv3"
readme = "README.md"
packages = [{include = "engine"}, {include = "viewer"}]
repository = "https://github.com/1jamesthompson1/TAIC-report-summary"

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.0.0"
bs4 = "^0.0.1"
pypdf = "^3.15.0"
requests = "^2.31.0"
tiktoken = "^0.4.0"
pyyaml = "^6.0.1"
argparse = "^1.4.0"
pandas = "^2.0.3"
regex = "^2023.8.8"
pytest = "^7.4.3"
pytest-xdist = "^3.5.0"
openai = "^1.4.0"

[tool.poetry.group.viewer.dependencies]
jinja2 = "^3.1.2"
flask = "^2.3.3"
pandas = "^2.0.3"
regex = "^2023.8.8"
nltk = "^3.8.1"

[tool.poetry.scripts]
engine = "engine.cli:cli"
viewer = "viewer.app:run"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
