[tool.poetry]
name = "taic-report-engine"
version = "0.1.0"
description = "An engine to use the powers of LLMs offered by openai to help analyse and interpret the accident investigation reports."
authors = ["James <1jamesthompson1@gmail.com>"]
license = "GPLv3"
readme = "README.md"
packages = [{include = "engine"}, {include = "viewer"}]

[tool.poetry.dependencies]
python = "^3.11"
openai = "^0.27.8"
python-dotenv = "^1.0.0"
bs4 = "^0.0.1"
pypdf = "^3.15.0"
requests = "^2.31.0"
tiktoken = "^0.4.0"
pyyaml = "^6.0.1"
argparse = "^1.4.0"
pandas = "^2.0.3"
regex = "^2023.8.8"


[tool.poetry.group.viewer.dependencies]
shiny = "^0.5.1"
jinja2 = "^3.1.2"

[tool.poetry.scripts]
cli = "engine.cli:cli"
app = "viewer.run:run"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
