name: Running Engine

on:
    schedule:
        - cron: '27 21 * * 0'

    workflow_dispatch:

jobs:
    run-engine:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - name: Install dependencies
              run: |
                pip install -r requirements.txt
                pip install poetry
            - name: Run Engine
              run: poetry run engine -t all
              env:
                OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                VOYAGE_API_KEY: ${{ secrets.VOYAGE_API_KEY }}
                ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
                AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
                AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
                db_URI: ${{ secrets.DB_URI }}